/*
  # Base Schema Setup - Fixed Order

  1. New Tables
    - `user_roles` - Role assignments for RBAC
    - `products` - Main product inventory
    - `subscriptions` - User subscription management
    - `produtos_estoque` - Stock products
    - `contagens_estoque` - Stock counts

  2. Security
    - RLS enabled on all tables
    - Admin-only INSERT/UPDATE/DELETE on user_roles
    - Owner-based access on products
    - Storage UPDATE policy for user-uploads bucket
*/

-- Enable UUID extension if not available
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- SECTION 1: APP_ROLE ENUM
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typname = 'app_role'
  ) THEN
    CREATE TYPE public.app_role AS ENUM ('admin', 'moderator', 'user');
  END IF;
END$$;

-- SECTION 2: USER_ROLES TABLE (minimal, without policies yet)
CREATE TABLE IF NOT EXISTS public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role public.app_role NOT NULL,
  created_at timestamptz DEFAULT now(),
  UNIQUE(user_id, role)
);

-- SECTION 3: HAS_ROLE HELPER FUNCTION (must exist BEFORE policies)
CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = _user_id AND role = _role
  );
$$;

-- SECTION 4: USER_ROLES POLICIES
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Admin-only INSERT policy (users CANNOT assign roles to themselves)
CREATE POLICY "User roles: admin can insert"
  ON public.user_roles
  FOR INSERT
  TO authenticated
  WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));

-- Admin-only UPDATE policy
CREATE POLICY "User roles: admin can update"
  ON public.user_roles
  FOR UPDATE
  TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::public.app_role))
  WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));

-- Admin-only DELETE policy
CREATE POLICY "User roles: admin can delete"
  ON public.user_roles
  FOR DELETE
  TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::public.app_role));

-- Users can read their own roles
CREATE POLICY "Users can read their own roles"
  ON public.user_roles
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

-- SECTION 5: PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid,
  name text DEFAULT '',
  lot text DEFAULT '',
  brand text DEFAULT '',
  manufacture_date date,
  expiry_date date,
  opening_date date,
  days_valid integer DEFAULT 0,
  use_by_date date,
  storage text DEFAULT 'ambiente',
  responsible text DEFAULT '',
  status text DEFAULT 'active',
  created_at timestamptz DEFAULT now(),
  expiry_date_entered boolean DEFAULT false,
  manufacture_date_entered boolean DEFAULT false
);

-- Trigger function to auto-populate user_id
CREATE OR REPLACE FUNCTION public.set_product_user_id()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF NEW.user_id IS NULL THEN
    NEW.user_id := auth.uid();
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_set_product_user_id ON public.products;
CREATE TRIGGER trg_set_product_user_id
BEFORE INSERT ON public.products
FOR EACH ROW
EXECUTE FUNCTION public.set_product_user_id();

-- Index for user_id filtering
CREATE INDEX IF NOT EXISTS idx_products_user_id ON public.products(user_id);

-- Products RLS
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Users can read their own products; admins can read all
CREATE POLICY "Users can read their own products"
  ON public.products
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid() OR public.has_role(auth.uid(), 'admin'::public.app_role));

-- Users can insert products (user_id auto-set); admins can insert
CREATE POLICY "Users can insert their own products"
  ON public.products
  FOR INSERT
  TO authenticated
  WITH CHECK ((user_id = auth.uid() OR user_id IS NULL) OR public.has_role(auth.uid(), 'admin'::public.app_role));

-- Users can update their own products; admins can update all
CREATE POLICY "Users can update their own products"
  ON public.products
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid() OR public.has_role(auth.uid(), 'admin'::public.app_role))
  WITH CHECK (user_id = auth.uid() OR public.has_role(auth.uid(), 'admin'::public.app_role));

-- Users can delete their own products; admins can delete all
CREATE POLICY "Users can delete their own products"
  ON public.products
  FOR DELETE
  TO authenticated
  USING (user_id = auth.uid() OR public.has_role(auth.uid(), 'admin'::public.app_role));

-- SECTION 6: SUBSCRIPTIONS TABLE
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'trialing',
  trial_start timestamptz NOT NULL DEFAULT now(),
  trial_end timestamptz NOT NULL DEFAULT (now() + interval '7 days'),
  plan text,
  payment_provider text,
  payment_id text,
  current_period_end timestamptz,
  mp_subscription_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

-- Users can read their own subscription
CREATE POLICY "Users can read own subscription"
  ON public.subscriptions
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

-- Anyone can insert (handled by signup trigger)
CREATE POLICY "Users can insert own subscription"
  ON public.subscriptions
  FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

-- Service role can update (for webhook)
CREATE POLICY "Service role can update subscriptions"
  ON public.subscriptions
  FOR UPDATE
  TO service_role
  USING (true)
  WITH CHECK (true);

-- SECTION 7: PRODUTOS_ESTOQUE TABLE
CREATE TABLE IF NOT EXISTS public.produtos_estoque (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  nome text NOT NULL,
  unidade_medida text NOT NULL,
  quantidade_por_unidade integer NOT NULL DEFAULT 1,
  unidade_conteudo text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.produtos_estoque ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own produtos_estoque"
  ON public.produtos_estoque
  FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- SECTION 8: CONTAGENS_ESTOQUE TABLE
CREATE TABLE IF NOT EXISTS public.contagens_estoque (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  produto_id uuid NOT NULL REFERENCES public.produtos_estoque(id),
  quantidade integer NOT NULL DEFAULT 0,
  quantidade_extra integer NOT NULL DEFAULT 0,
  unidade_quantidade_extra text NOT NULL DEFAULT 'porcoes',
  quantidade_total numeric NOT NULL DEFAULT 0,
  data_contagem timestamptz NOT NULL DEFAULT now(),
  responsavel text,
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.contagens_estoque ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own contagens_estoque"
  ON public.contagens_estoque
  FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- SECTION 9: STORAGE UPDATE POLICY
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM storage.buckets WHERE id = 'user-uploads') THEN
    DROP POLICY IF EXISTS "Users can update their own uploads" ON storage.objects;
    
    EXECUTE $p$
      CREATE POLICY "Users can update their own uploads"
        ON storage.objects
        FOR UPDATE
        TO authenticated
        USING (bucket_id = 'user-uploads' AND (storage.foldername(name))[1] = auth.uid()::text)
        WITH CHECK (bucket_id = 'user-uploads' AND (storage.foldername(name))[1] = auth.uid()::text)
    $p$;
  END IF;
EXCEPTION WHEN others THEN NULL;
END $$;
