// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obrarfirqdoidxqlvykg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9icmFyZmlycWRvaWR4cWx2eWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMDA4NDIsImV4cCI6MjA1NTc3Njg0Mn0.lVfTStOnZjw9jfKUTB5eDv8o8aCue4faqGwL5spb_WQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});